### ISSUE TITLE
Hmm...

### ISSUE THREAD

**Issue by daimeng** [chenhi/aiml-exercises#1]
How to run :0?

I run `python mdp_test.py` and get:
```
Traceback (most recent call last):
  File "/home/daimeng/ml/aiml-exercises/game_learner/mdp_test.py", line 160, in <module>
    game.batch_learn(lr, iter, eps, eplen)
  File "/home/daimeng/ml/aiml-exercises/game_learner/qlearn.py", line 248, in batch_learn
    queue[p] = [s, a, r[p]]
                      ~^^^
TypeError: 'int' object is not subscriptable
```

**Comment by chenhi** [comment]
GIT GUD?

deleted the offending code, was never really implemented / not meant to be
